export enum AMLSupervioryBodiesFormatted {
    "association-of-chartered-certified-accountants-acca" = "Association of Chartered Certified Accountants (ACCA)",
    "association-of-accounting-technicians-aat" = "Association of Accounting Technicians (AAT)",
    "association-of-international-accountants-aia" = "Association of International Accountants (AIA)",
    "association-of-taxation-technicians-att" = "Association of Taxation Technicians (ATT)",
    "chartered-institute-of-legal-executives-cilex" = "Chartered Institute of Legal Executives (CILEx)",
    "chartered-institute-of-management-accountants-cima" = "Chartered Institute of Management Accountants (CIMA)",
    "chartered-institute-of-taxation-ciot" = "Chartered Institute of Taxation (CIOT)",
    "council-for-licensed-conveyors-clc" = "Council for Licensed Conveyancers (CLC)",
    "department-for-the-economy-northern-ireland" = "Department for the Economy Northern Ireland",
    "faculty-of-advocates" = "Faculty of Advocates",
    "faculty-office-of-the-archbishop-of-canterbury" = "Faculty Office of the Archbishop of Canterbury",
    "financial-conduct-authority-fca" = "Financial Conduct Authority (FCA)",
    "gambling-commission" = "Gambling Commission",
    "bar-standards-board-bsb" = "Bar Standards Board (BSB)",
    "general-council-of-the-bar-of-northern-ireland" = "General Council of the Bar of Northern Ireland",
    "institute-of-accountants-bookkeepers-iab" = "Institute of Accountants and Bookkeepers (IAB)",
    "insolvency-practitioners-association-ipa" = "Insolvency Practitioners Association (IPA)",
    "institute-of-certified-bookkeepers-icb" = "Institute of Certified Bookkeepers",
    "institute-of-chartered-accountants-in-england-and-wales-icaew" = "Institute of Chartered Accountants in England and Wales (ICAEW)",
    "institute-of-chartered-accountants-in-ireland-icai" = "Institute of Chartered Accountants in Ireland (ICAI)",
    "institute-of-chartered-accountants-of-scotland-icas" = "Institute of Chartered Accountants of Scotland (ICAS)",
    "institute-of-financial-accountants-ifa" = "Institute of Financial Accountants (IFA)",
    "law-society-of-northern-ireland" = "Law Society of Northern Ireland",
    "law-society-of-scotland" = "Law Society of Scotland",
    "law-society-ew-solicitors-regulation-authority-sra" = "Solicitors Regulation Authority (SRA) Solicitors in England and Wales",
    "hm-revenue-customs-hmrc" = "HMRC"
}
