export enum AMLSupervisoryBodies {
      "Association of Chartered Certified Accountants (ACCA)",
      "Association of Accounting Technicians (AAT)",
      "Association of International Accountants (AIA)",
      "Association of Taxation Technicians (ATT)",
      "Chartered Institute of Legal Executives (CILEx)",
      "Chartered Institute of Management Accountants (CIMA)",
      "Chartered Institute of Taxation (CIOT)",
      "Council for Licensed Conveyancers (CLC)",
      "Department for the Economy Northern Ireland",
      "Faculty of Advocates",
      "Faculty Office of the Archbishop of Canterbury",
      "Financial Conduct Authority (FCA)",
      "Gambling Commission",
      "General Council of the Bar",
      "General Council of the Bar of Northern Ireland",
      "HMRC",
      "Institute of Accountants and Bookkeepers (IAB)",
      "Insolvency Practitioners Association (IPA)",
      "Institute of Certified Bookkeepers",
      "Institute of Chartered Accountants in England and Wales (ICAEW)",
      "Institute of Chartered Accountants in Ireland (ICAI)",
      "Institute of Chartered Accountants of Scotland (ICAS)",
      "Institute of Financial Accountants (IFA)",
      "Law Society of Northern Ireland",
      "Law Society of Scotland",
      "Solicitors Regulation Authority (SRA) Solicitors in England and Wales"
}
