export enum AMLSupervisoryBodies {
      ACCA = "Cymdeithas y Cyfrifwyr Ardystiedig Siartredig (ACCA",
      AAT = "Cymdeithas Technegwyr Cyfrifyddu (AAT)",
      AIA = "Cymdeithas y Cyfrifwyr Rhyngwladol (AIA)",
      ATT = "Cymdeithas y Technegwyr Trethiant (ATT)",
      CILEX = "Sefydliad Siartredig Gweithredwyr Cyfreithiol (CILEx)",
      CIMA = "Sefydliad Siartredig y Cyfrifwyr Rheoli (CIMA)",
      CIOT = "Sefydliad Siartredig Trethi (CIOT)",
      CLC = "Cyngor ar gyfer Trawsgludwyr trwyddedig (CLC)",
      DENI = "Adran yr Economi Gogledd Iwerddon",
      FA = "Cyfadran yr Eiriolwyr",
      FO = "Swyddfa Gyfadran Archesgob Caergaint",
      FCA = "Awdurdod Ymddygiad Ariannol (FCA)",
      GC = "Comisiwn Hapchware",
      BSB = "Bwrdd Safonau'r Bar (BSB)",
      BONI = "Cyngor Cyffredinol Bar Gogledd Iwerddon",
      HMRC = "CThEF",
      IAB = "Sefydliad Cyfrifwyr a Chadwyr Llyfrau (IAB)",
      IPA = "Cymdeithas Ymarferwyr Ansolfedd (IPA)",
      ICB = "Sefydliad y Llyfrwyr Ardystiedig",
      ICAEW = "Sefydliad y Cyfrifwyr Siartredig yng Nghymru a Lloegr (ICAEW)",
      ICAI = "Sefydliad y Cyfrifwyr Siartredig yn Iwerddon (ICAI)",
      ICAS = "Sefydliad Cyfrifwyr Siartredig yr Alban (ICAS)",
      IFA = "Sefydliad y Cyfrifwyr Ariannol (IFA)",
      LSNI = "Cymdeithas Cyfreithwyr Gogledd Iwerddon",
      LSS = "Cymdeithas Cyfreithwyr yr Alban",
      SRA = "Awdurdod Rheoleiddio Cyfreithwyr (SRA) Cyfreithwyr yng Nghymru a Lloegr"
}
