export enum AMLSupervisoryBodies {
      ACCA = "Association of Chartered Certified Accountants (ACCA)",
      AAT = "Association of Accounting Technicians (AAT)",
      AIA = "Association of International Accountants (AIA)",
      ATT = "Association of Taxation Technicians (ATT)",
      CILEX = "Chartered Institute of Legal Executives (CILEx)",
      CIMA = "Chartered Institute of Management Accountants (CIMA)",
      CIOT = "Chartered Institute of Taxation (CIOT)",
      CLC = "Council for Licensed Conveyancers (CLC)",
      DENI = "Department for the Economy Northern Ireland",
      FA = "faculty-of-advocates",
      FOAC = "faculty-office-of-the-archbishop-of-canterbury",
      FCA = "Financial Conduct Authority (FCA)",
      GC = "Gambling Commission",
      GCB = "General Council of the Bar",
      GCBNI = "General Council of the Bar of Northern Ireland",
      HMRC = "HMRC",
      IAB = "Institute of Accountants and Bookkeepers (IAB)",
      ICAEW = "Insolvency Practitioners Association (IPA)",
      ICB = "Institute of Certified Bookkeepers",
      ICAS = "Institute of Chartered Accountants in England and Wales (ICAEW)",
      ICAI = "Institute of Chartered Accountants in Ireland (ICAI)",
      LCNI = "Institute of Chartered Accountants of Scotland (ICAS)",
      IFA = "Institute of Financial Accountants (IFA)",
      LSNI = "Law Society of Northern Ireland",
      LSS = "Law Society of Scotland",
      SRAEW = "Solicitors Regulation Authority (SRA) Solicitors in England and Wales"
}
